import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fef6e4',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        backgroundColor: '#fff',
        elevation: 3,
    },
    profile: { flexDirection: 'row', alignItems: 'center' },
    profileImage: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: 10,
    },
    profileInfo: { marginLeft: 8 },
    nickname: { fontWeight: 'bold', fontSize: 16 },
    level: { fontSize: 14, color: 'gray' },
    hearts: { flexDirection: 'row', alignItems: 'center' },
    heartCount: { marginLeft: 5, fontSize: 16 },
    settingsIcon: { padding: 10 },
    gameContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-around', marginTop: 10 },
    gameCard: {
        width: '45%',
        height: 335,
        backgroundColor: '#fff',
        marginVertical: 8,
        borderRadius: 10,
        padding: 4,
        elevation: 6,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#000',
    },
    gameImage: { width: '100%', height: 255, borderRadius: 8 },
    gameTitle: { marginTop: 10, fontWeight: 'bold', fontSize: 20},
    hashtagContainer: { flexDirection: 'row', marginTop: 5 },
    hashtag: { marginHorizontal: 3, fontSize: 12, backgroundColor: '#eee', padding: 2, borderRadius: 5 },
    matchButton: {
        backgroundColor: '#6f96ff',
        padding: 15,
        alignItems: 'center',
        borderRadius: 20,
        margin: 20,
    },
    imagePlaceholder: {
        width: 100,
        height: 100,
        backgroundColor: '#EAEAEA',
        borderRadius: 10,
        marginBottom: 10,
    },
    matchButtonText: { color: '#fff', fontSize: 18 },

    // ✅ 설정 모달 스타일 추가
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        width: '80%',
        padding: 20,
        backgroundColor: '#fff',
        borderRadius: 10,
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 15,
    },
    settingItem: {
        width: '100%',
        alignItems: 'center',
        marginBottom: 10,
    },
    slider: {
        width: '80%',
    },
    modalButtonDelete: {
        padding: 10,
        width: '100%',
        alignItems: 'center',
        backgroundColor: 'red',
        borderRadius: 10,
        marginVertical: 5,
    },
    modalButtonLogout: {
        padding: 10,
        width: '100%',
        alignItems: 'center',
        backgroundColor: '#555',
        borderRadius: 10,
        marginVertical: 5,
    },
    closeButton: {
        marginTop: 10,
        padding: 10,
        backgroundColor: '#ddd',
        width: '100%',
        alignItems: 'center',
        borderRadius: 10,
    },
    metaContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 5,
    },
    categoryText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#4A90E2',
    },
    separator: {
        fontSize: 12,
        color: '#999',
        marginHorizontal: 5,
    },
    hashtagText: {
        fontSize: 12,
        color: '#666',
    },
});
