import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  safeArea: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    marginVertical: 12,
  },
  headerText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  timerContainer: {
    padding: 10,
    alignItems: 'center',
  },
  timerWrapper: {
    width: '100%',
    alignItems: 'center',
    zIndex: 20,
  },
  timerBar: {
    width: '50%',
    height: 10,
    backgroundColor: '#ddd',
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom: 4,
  },
  timerProgress: {
    height: '100%',
    backgroundColor: '#4CAF50',
  },
  timerText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  boardContainer: {
    alignSelf: 'center',
    marginVertical: 8,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  cell: {
    width: 38,
    height: 54,
    margin: 2,
    backgroundColor: '#fff',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  emptyCell: {
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  chipImage: {
    width: 20,
    height: 20,
    zIndex: 10,
    position: 'absolute',
  },
  handContainer: {
    width: '100%',
    flexDirection: 'row',
    padding: 0,
    backgroundColor: 'transparent',
    marginBottom: 0,
    height: 54,
  },
  handScrollView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flex: 1,
    gap: 4,
    height: 54,
  },
  card: {
    width: 50,
    height: 60,
    elevation: 5,
    resizeMode: 'cover',
  },
  selectedCard: {
    borderWidth: 2,
    borderColor: '#007AFF',
  },
  cardImage: {
    width: 34,
    height: 50,
  },
  turnIndicator: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: 10,
    borderRadius: 20,
  },
  turnText: {
    color: 'white',
    fontSize: 16,
  },
  validCell: {
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    borderColor: 'rgba(255, 0, 0, 1)',
    borderWidth: 2,
    zIndex: 10,
    width: 35,
    height: 50,
  },
  FrogCell: {
    borderColor: 'rgb(255, 0, 0)',
    borderWidth: 4,
    zIndex: 10,
    width: 35,
    height: 50,
  },
  myFrogCell: {
    width: 35,
    height: 50,
    margin: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,0,0,0.15)',
    borderRadius: 4,
    borderWidth: 4,
    borderColor: '#FF0000',
    overflow: 'hidden',
    zIndex: 10,
  },
  opponentFrogCell: {
    width: 35,
    height: 50,
    margin: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(128,0,128,0.15)',
    borderRadius: 4,
    borderWidth: 4,
    borderColor: '#800080',
    overflow: 'hidden',
    zIndex: 10,
  },
  timerRowWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: -20,
    marginBottom: 8,
    zIndex: 20,
    paddingHorizontal: 20,
  },
  lastCardsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  lastCardWrapper: {
    width: 30,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 4,
    padding: 2,
  },
  lastCardImage: {
    width: 26,
    height: 36,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#fff',
    backgroundColor: '#222',
  },
  turnIndicatorFixed: {
    position: 'absolute',
    top: 10,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderRadius: 18,
    zIndex: 100,
    alignSelf: 'center',
  },
  turnTextFixed: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  doraHandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    gap: 10,
  },
  doraArea: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    borderRadius: 8,
    padding: 10,
    marginRight: 10,
    minWidth: 50,
    height: 54,
  },
  handArea: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    height: 54,
    flexDirection: 'row',
  },
  doraLabel: {
    fontSize: 14,
    color: '#000',
    fontWeight: 'bold',
  },
  doraImage: {
    width: 34,
    height: 50,
  },
  handWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  handRow: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  handCardWrapper: {
    marginHorizontal: 2,
    alignItems: 'center',
    height: 54,
    justifyContent: 'center',
  },
  handCardImage: {
    width: 34,
    height: 50,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 16,
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  actionButton: {
    backgroundColor: '#4A90E2',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 22,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  discardPileContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,

  },
  discardInfoContainer: {
    alignItems: 'center',
  },
  discardCardImage: {
    width: 30,
    height: 40,
    marginBottom: 2,
    gap: 2,

  },
  discardCountsContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    padding: 2,
    borderRadius: 4,
  },
  discardCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  colorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  greenDot: {
    backgroundColor: '#4CAF50',
  },
  redDot: {
    backgroundColor: '#F44336',
  },
  normalDot: {
    backgroundColor: '#9E9E9E',
  },
  discardCountText: {
    color: '#fff',
    fontSize: 9,
  },
}); 