import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  safeArea: {
    flex: 1,
  },
  header: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  headerText: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
  },
  timerContainer: {
    padding: 10,
    alignItems: 'center',
  },
  timerWrapper: {
    width: '100%',
    alignItems: 'center',
    zIndex: 20,
    marginTop:-50,
  },
  timerBar: {
    width: '50%',
    height: 10,
    backgroundColor: '#ddd',
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom: 4,
  },
  timerProgress: {
    height: '100%',
    backgroundColor: '#4CAF50',
  },
  timerText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  boardContainer: {
    flex: 1,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginTop:-40,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cell: {
    width: 35,
    height: 50,
    margin: 1,
  },
  chipImage: {
    width: 20,
    height: 20,
    zIndex: 10,
    position: 'absolute',
  },
  handContainer: {
    width: '70%',
    alignSelf: 'center',
    flexDirection: 'row',
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginBottom: 5,
  },
  handScrollView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  card: {
    width: 50,
    height: 60,
    elevation: 5,
    resizeMode: 'cover',
  },
  selectedCard: {
    borderWidth: 2,
    borderColor: '#007AFF',
  },
  cardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  turnIndicator: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: 10,
    borderRadius: 20,
  },
  turnText: {
    color: 'white',
    fontSize: 16,
  },
  validCell: {
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    borderColor: 'rgba(255, 0, 0, 1)',
    borderWidth: 2,
    zIndex: 10,
    width: 35,
    height: 50,
  },
  sequenceCell: {
    borderColor: 'rgb(255, 0, 0)',
    borderWidth: 4,
    zIndex: 10,
    width: 35,
    height: 50,
  },
  mySequenceCell: {
    backgroundColor: 'rgba(255,0,0,0.35)',
    borderColor: '#FF0000',
    borderWidth: 2,
    zIndex: 10,
    width: 35,
    height: 50,
  },
  timerRowWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginTop: -20,
    marginBottom: 8,
    zIndex: 20,
  },
  lastCardWrapper: {
    width: 40,
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lastCardImage: {
    width: 32,
    height: 45,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#fff',
    backgroundColor: '#222',
  },
  turnIndicatorFixed: {
    position: 'absolute',
    top: 10,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderRadius: 18,
    zIndex: 100,
    alignSelf: 'center',
  },
  turnTextFixed: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
}); 