import { StyleSheet, Dimensions } from 'react-native';
import { scale, verticalScale } from 'react-native-size-matters';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
    // 전체 배경 이미지 스타일
    background: {
        flex: 1,
        resizeMode: 'cover',
    },
    backgroundImage: {
        resizeMode: 'cover',
    },
    // 컨테이너: 가운데 정렬
    container: {
        flex: 1,
        alignItems: 'center',
    },
    resultContainer: {
        flex: 1,
        alignContent: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: verticalScale(50),
        width: '90%',
        borderWidth: scale(1),
        borderRadius: scale(10),
        marginBottom: verticalScale(50),
        backgroundColor: '#F5EDD8',
    },
    clearConatiner: {
        flexDirection: 'column',
        width: '100%',
        height: verticalScale(100),
        borderRadius: scale(10),
        alignItems: 'center',
    },
    clearIcon: {
        width: '100%',
        height: verticalScale(60),
        resizeMode: 'contain',
        marginBottom: verticalScale(10),
    },
    clearTextContainer: {
        width: scale(200),
        height: verticalScale(35),
        backgroundColor: '#C4C4C4',
        borderRadius: scale(20),
        borderWidth: scale(1.5),
        justifyContent: 'center',
    },
    clearText: {
        fontSize: scale(20),
        textAlign: 'center',
        fontWeight: 'bold',
        color: '#FFFFFF',
        textShadowColor: '#000000',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 1,
    },
    // 결과 컨테이너 스타일
    resultScoreContainer: {
        padding: scale(16),
        marginTop: verticalScale(30),
        backgroundColor: '#F0E3C3',
        borderRadius: scale(14),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 6,
        width: '90%',
        alignSelf: 'center',
        borderWidth: scale(2),
        borderColor: '#BFA276',
    },
    resultScoreTitle: {
        fontSize: scale(18),
        fontWeight: 'bold',
        marginBottom: verticalScale(12),
        color: '#5F4B32',
        letterSpacing: 1,
        textAlign: 'center',
    },
    resultScoreRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: verticalScale(8),
        paddingHorizontal: scale(10),
    },
    resultScoreName: {
        fontSize: scale(16),
        fontWeight: '500',
        color: '#5F4B32',
    },
    resultScoreValue: {
        fontSize: scale(16),
        marginRight: scale(8),
        color: '#5F4B32',
    },
    resultScoreStatus: {
        fontWeight: 'bold',
        fontSize: scale(16),
    },
    winnerText: {
        color: '#2ecc40',
    },
    loserText: {
        color: '#e74c3c',
    },
    profilesRootContainer: {
        width: '90%',
        marginTop: verticalScale(10),
        marginBottom: verticalScale(50),
    },
    profilesContainer: {
        backgroundColor: '#F0E3C3',
        borderRadius: scale(10),
        borderWidth: scale(2),
        borderColor: '#BFA276',
        padding: scale(10),
    },
    profileRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: verticalScale(8),
        paddingHorizontal: scale(10),
        backgroundColor: '#FFF',
        borderRadius: scale(8),
        marginBottom: verticalScale(8),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    profileIconContainer: {
        width: scale(40),
        height: scale(40),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFD700',
        borderRadius: scale(20),
        marginRight: scale(10),
    },
    profileTwoIconContainer: {
        width: scale(40),
        height: scale(40),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#C0C0C0',
        borderRadius: scale(20),
        marginRight: scale(10),
    },
    profileImageContainer: {
        width: scale(40),
        height: scale(40),
        borderRadius: scale(20),
        borderWidth: scale(2),
        borderColor: '#BFA276',
        backgroundColor: '#FFF',
        marginRight: scale(10),
    },
    profileImage: {
        width: '100%',
        height: '100%',
        borderRadius: scale(18),
    },
    profileName: {
        flex: 1,
        fontSize: scale(16),
        fontWeight: '600',
        color: '#5F4B32',
    },
    profileScoreContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: scale(20),
        borderWidth: scale(1),
        borderColor: '#BFA276',
    },
    profileTwoScoreContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: scale(20),
        borderWidth: scale(1),
        borderColor: '#BFA276',
    },
    profileScore: {
        fontSize: scale(16),
        fontWeight: 'bold',
        marginLeft: scale(8),
    },
    coinIcon: {
        width: scale(20),
        height: scale(20),
        marginRight: scale(4),
    },
    medalIcon: {
        marginVertical: scale(10),
        zIndex: 2,
    },
    medalTwoIcon: {
        marginVertical: scale(10),
        zIndex: 2,
    },
    ResultButtonContainer: {
        width: '50%',
        height: verticalScale(50),
        bottom: verticalScale(30),
        alignItems: 'center',
    },
    resultButton: {
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: verticalScale(45),
        backgroundColor: '#BFA276',
        borderRadius: scale(25),
        borderWidth: scale(2),
        borderColor: '#8B7355',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 15,
    },
    resultButtonText: {
        color: '#FFF',
        fontSize: scale(18),
        fontWeight: 'bold',
        textAlign: 'center',
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
});
