name: Auto PR
on:
  push:
    branches:
      - "epic/**"
      - "task/**"
      - "feature/**"
      - "fix/**"
      - "refactor/**"

jobs:
  create-or-update-pr:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PR body from commits
        id: body
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo
            const head = context.ref.replace('refs/heads/', '')
            // default branch
            const { data: repoInfo } = await github.rest.repos.get({owner, repo})
            const base = repoInfo.default_branch
            const { data: cmp } = await github.rest.repos.compareCommits({owner, repo, base, head})
            const lines = cmp.commits.map(c => `- ${c.commit.message.split('\n')[0]} (@${c.author?.login || 'bot'})`).join('\n')
            const template = `
## 요약
- 변경 목적:

## 변경 사항
${lines || '- (커밋 없음)'}

## 체크리스트
- [ ] 테스트 통과
- [ ] 문서/릴리즈노트 갱신

## 이슈 링크
Closes #
`
            core.setOutput('text', template)

      - name: Create/Update PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "feat: ${{ github.ref_name }}"
          body: "${{ steps.body.outputs.text }}"
          base: "${{ github.event.repository.default_branch }}"
          branch: "autopr/${{ github.ref_name }}"
          labels: "stage/review"
          draft: true
